version: '3.4'
services:
    api:
        build: ./hypervisor
        ports:
            - 8000:8000
        volumes:
            - /var/run/libvirt:/var/run/libvirt
            - /home/pushpender/Apps/hypervisor-django-api/hypervisor:/src/app
            - /usr/bin/docker:/usr/bin/docker
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
            - BASE_PATH=/home/pushpender/Apps/hypervisor-django-api/hypervisor
    websockify:
        build: ./websockify
        ports:
            - 6080:6080
        volumes:
            - /home/pushpender/Apps/hypervisor-django-api/websockify:/src/app
        network_mode: host
    terminal:
        build: ./docker-console
        ports:
            - 8766:8766
        volumes:
            - /home/pushpender/Apps/hypervisor-django-api/docker-console/console:/src/app
            - /var/run/docker.sock:/var/run/docker.sock
