# Generated by Django 2.2.2 on 2019-07-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isomodel',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
