# Generated by Django 2.2.2 on 2019-07-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0002_auto_20190705_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isomodel',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
