# Generated by Django 2.2.2 on 2019-07-05 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isos', '0003_auto_20190705_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='isomodel',
            name='file',
            field=models.FileField(default='default.iso', upload_to=''),
        ),
    ]
